### ISSUE TITLE
你cookie那是怎么设置的

### ISSUE THREAD

**Issue by Tyux** [DullSword/GLaDOS-CheckIn#1]

**Comment by xoub-nar** [comment]
在登录glados按F12打开开发者找到cookie

**Comment by DullSword** [comment]
不好意思，现在才看到。不太清楚怎么设置是什么意思，就是如图所示，点击Settings，然后点击Secrets，接着点击New repository secrets创建密钥，name就是“COOKIE”，value则是你账号对应的cookie。如果是不知道cookie如何获取，README文档里已经增加了“准备工作”的说明。
