### ISSUE TITLE
新版本secret变量的关键字变了，希望高亮提醒下

### ISSUE THREAD

**Issue by z-henry** [DullSword/GLaDOS-CheckIn#10]
今天更新了下发现怎么都无法签到，查日志发现没权限
仔细看才看到，从COOKIE变成COOKIES
不知道是不是我太久没更新了，
建议主页的文档提醒一下 XD

**Comment by DullSword** [comment]
版本更新带来的变动，经过思考，我决定将这部分内容放在文档中的 [更新日志](https://github.com/DullSword/GLaDOS-CheckIn#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97) 里，减少新使用者的理解成本。

不过之前相关的说明确实是遗漏了更新密钥的部分，我的锅，文档已修改更新，同时将“更新日志”的跳转链接放在开头，尽可能减少更新版本带来的困扰。

`COOKIE` 更改为 `COOKIES`，是希望能贴合支持多账号的语义。也想过保留 `COOKIE`，但天真的我以为在能正常使用的情况下用户并不会主动更新，所以我决定大刀阔斧地一步到位。对于带来的困扰与不便，我很抱歉，在之后尽可能避免该类错误。

**Comment by z-henry** [comment]
谢谢，邮件已收到！

**Comment by z-henry** [comment]
谢谢，邮件已收到！
