### ISSUE TITLE
pushplus 请求json的地址换了，新地址：http://pushplus.hxtrip.com/send

### ISSUE THREAD

**Issue by mikemhm** [DullSword/GLaDOS-CheckIn#13]
pushplus 请求json的地址换了，新地址：http://pushplus.hxtrip.com/send

**Comment by DullSword** [comment]
[http://pushplus.hxtrip.com](http://pushplus.hxtrip.com) 和 [https://www.pushplus.plus](https://www.pushplus.plus)，当时选择推送的时候我就发现这2个很像，然后我简单地根据我多年冲浪的经验选择了 [https://www.pushplus.plus](https://www.pushplus.plus)。我看了下这几天签到情况，接口表现正常，[https://www.pushplus.plus](https://www.pushplus.plus) 没有相关改动。

至于 [http://pushplus.hxtrip.com](http://pushplus.hxtrip.com) 和 [https://www.pushplus.plus](https://www.pushplus.plus) 我也不清楚只是新旧地址问题还是主体不同问题。
