### ISSUE TITLE
到官网续期提示不能继续免费试用

### ISSUE THREAD

**Issue by llyrz** [DullSword/GLaDOS-CheckIn#14]
到官网续期提示不能继续免费试用,提示只能订购,无法继续免费试用,免费试用时间有限制吗?

**Comment by DullSword** [comment]
不是特别明白你说的“续期”和“免费使用时间有限制”是什么意思。关于试用的话，现在的机制我不清楚，我开始用的时候好像是试用3天，然后前一个月每天签到都送1天，一个月之后每天签到变为有33%几率送一天。

**Comment by llyrz** [comment]
感谢回复,我续期的意思就是签到,之前3个月签到能一直送一天免费试用,平时Google也够用了,最近微信方糖提示签到没有天数了,我去网站登录看了下,提示只能付费购买套餐了,免费试用没有资格了,没有其他的意思,就是询问一下,感谢感谢

**Comment by DullSword** [comment]
> 感谢回复,我续期的意思就是签到,之前3个月签到能一直送一天免费试用,平时Google也够用了,最近微信方糖提示签到没有天数了,我去网站登录看了下,提示只能付费购买套餐了,免费试用没有资格了,没有其他的意思,就是询问一下,感谢感谢

你说的官网是指Server酱还是GlaDOS？如果是Server酱的话，现在新版本已经改为用pushplus推送了，这可能是你签到不了的原因；如果是在GlaDOS官网上进行手动签到都签不了的话，那就没办法了。
