### ISSUE TITLE
为什么似乎没有正常运行？

### ISSUE THREAD

**Issue by lankerr** [DullSword/GLaDOS-CheckIn#17]
是不是需要在这个时间段一直联网？
或者说需要电脑在此时间段处于待机/开机状态
由于不清楚github的代码运行原理555

**Comment by DullSword** [comment]
跟本地没有关系，你可以理解为这一切都是在 Github 的服务器上运行的。

没有正常运行的原因可能是因为有延迟，也可能是刚好碰到 Github Actions 出现问题 #5 ，或者没有填写对信息等等。可以尝试查看 log 获得更多信息。

![image](https://user-images.githubusercontent.com/40877476/167339461-4c24f644-65bc-4a97-afb7-04009278e9f9.png)

**Comment by lankerr** [comment]
收到，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月9日(周一) 中午12:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DullSword/GLaDOS-CheckIn] 为什么似乎没有正常运行？ (Issue #17)




 
跟本地没有关系，你可以理解为这一切都是在 Github 的服务器上运行的。
 
没有正常运行的原因可能是因为有延迟，也可能是刚好碰到 Github Actions 出现问题 #5 ，或者没有填写对信息等等。可以尝试查看 log 获得更多信息。
