### ISSUE TITLE
今天突然提示oops，token error

### ISSUE THREAD

**Issue by greenwave1987** [DullSword/GLaDOS-CheckIn#19]
今天突然提示oops，token error，更新了cookie还是提示这个

**Comment by Cholly-Tse** [comment]
checkin.js 中token的值需要由"glados_network"更新为"glados.network"。

**Comment by mima454188** [comment]
> checkin.js 中token的值需要由"glados_network"更新为"glados.network"。

谢谢，已经更改。

**Comment by DullSword** [comment]
> checkin.js 中token的值需要由"glados_network"更新为"glados.network"。

是的，感谢贡献。

**Comment by DullSword** [comment]
昨早还没问题，晚上就已经更改了 #18

**Comment by RouJiANG-14** [comment]
感激速度更新！
