### ISSUE TITLE
运行超过60天后，如果没有修改的话Github自动关闭了workflow，该怎么解决

### ISSUE THREAD

**Issue by LiJT** [DullSword/GLaDOS-CheckIn#20]
求大佬指点一下怎么达成一劳永逸的方法，谢谢！

**Comment by DullSword** [comment]
> 求大佬指点一下怎么达成一劳永逸的方法，谢谢！

"Github自动关闭了workflow"具体是指什么情况？

**Comment by LiJT** [comment]
> 

GitHub Actions scheduled workflow
 
 
Scheduled workflows are disabled automatically after 60 days of repository inactivity. 

因为长时间不活动没有修改，github就是关闭这个workflow

**Comment by tyIceStream** [comment]
可以考虑一下[gautamkrishnar/keepalive-workflow@master](https://github.com/gautamkrishnar/keepalive-workflow)

**Comment by LiJT** [comment]
> 可以考虑一下[gautamkrishnar/keepalive-workflow@master](https://github.com/gautamkrishnar/keepalive-workflow)

小弟不才，没看懂这个应该怎么合并到咱们目前有的workflow里面。。。

**Comment by tyIceStream** [comment]
把
      - uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings
这行字加在yml文件的最后一行

**Comment by DullSword** [comment]
> > 
> 
> GitHub Actions scheduled workflow
> 
> Scheduled workflows are disabled automatically after 60 days of repository inactivity.
> 
> 因为长时间不活动没有修改，github就是关闭这个workflow

我自己没出现这种情况，所以不是很清楚，翻阅了下文档，确实是有这样的限制。

- [Disabling and enabling workflows](https://docs.github.com/cn/actions/learn-github-actions/usage-limits-billing-and-administration#disabling-and-enabling-workflows)

**Comment by DullSword** [comment]
> 把 - uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings 这行字加在yml文件的最后一行

我查找了下，这应该就是比较简单好用的实现，欢迎提交PR。

**Comment by LiJT** [comment]
> 把 - uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings 这行字加在yml文件的最后一行

谢谢！
