### ISSUE TITLE
github action定时任务不运行

### ISSUE THREAD

**Issue by Thund1R** [DullSword/GLaDOS-CheckIn#25]
不知道因为啥github action定时任务始终不运行，测了好多次，求大佬帮助

**Comment by Thund1R** [comment]
本来pr了一个版本修改了些推送标题，结果我自己的定时任务跑不起来我就关了哈哈哈哈

**Comment by Thund1R** [comment]
感觉是官方给我停了，小号能跑哈哈哈

**Comment by DullSword** [comment]
不是大佬。信息有点少，不清楚是哪个步骤有问题。可以手动运行吗？

![1653108160(1)](https://user-images.githubusercontent.com/40877476/169635640-ae1cf38c-2549-403d-97cb-a69d48c14386.png)

**Comment by Thund1R** [comment]
莫名其妙大号能跑起来了哈哈哈，工作流执行都是成功的，之前不知道为啥他总是不触发schedule，刚刚看了下今天成功触发了。可能是之前排队时间过分的长了，谢谢了~
