### ISSUE TITLE
[question/help]: Pushplus要暂停服务了

### ISSUE THREAD

**Issue by House-Leo** [DullSword/GLaDOS-CheckIn#28]
### 问题

刚刚公众号收到消息，好像要暂停免费服务了

**Comment by DullSword** [comment]
你看的应该是 http://pushplus.hxtrip.com/ ，目前项目使用的是 https://www.pushplus.plus/ 。

https://github.com/DullSword/GLaDOS-CheckIn/issues/13#issuecomment-1099149535
