### ISSUE TITLE
[question/help]:项目显示成功运行，但是没有自动签到与微信推送？ 

### ISSUE THREAD

**Issue by Guichena** [DullSword/GLaDOS-CheckIn#29]
### 问题

![U6`$8)G$C@30`(Y9~1IVSZI](https://user-images.githubusercontent.com/102907545/172761290-7169d609-a896-4b2d-be24-b0f5b105a05d.png)

**Comment by DullSword** [comment]
可以贴一下工作流日志吗？

1.  点击具体工作流
2.  点击 build
3.  点击右上角选项，选择 "View raw logs"
4.  复制logs，去除“账号”（即邮箱）信息

**Comment by Guichena** [comment]
大佬，根据你的操作他回复的是error。Fastly error: unknown domain: pipelines.actions.githubusercontent.com. Please check that this domain has been added to a service.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月9日(星期四) 晚上10:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DullSword/GLaDOS-CheckIn] [question/help]:项目显示成功运行，但是没有自动签到与微信推送？  (Issue #29)





 
可以贴一下工作流日志吗？
  
点击具体工作流
 
点击 build
 
点击右上角选项，选择 "View raw logs"
 
复制logs，去除“账号”（即邮箱）信息

**Comment by Guichena** [comment]
> 大佬，根据你的操作他回复的是error。快速错误：未知域：pipelines.actions.githubusercontent.com。请检查此域是否已添加到服务中。
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年6月9日(星期四) 晚上10:44 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [DullSword/GLaDOS-CheckIn] [question/help]:项目显示成功运行，但是没有自动签到与微信推送？ (Issue #29) 可以贴一下工作流日志吗？ 点击具体工作流 点击 build 点击右上角选项，选择 "View raw logs" 复制logs，去除“账号”（即邮箱）信息 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Fastly error: unknown domain: pipelines.actions.githubusercontent.com. Please check that this domain has been added to a service.

Details: cache-itm18827-ITM

**Comment by DullSword** [comment]
试试重新设置下`COOKIES`密钥。看起来是 cookie 有非法字符，可能复制粘贴时误入了其他字符。

[三、设置密钥](https://github.com/DullSword/GLaDOS-CheckIn#%E4%B8%89%E8%AE%BE%E7%BD%AE%E5%AF%86%E9%92%A5)

**Comment by Guichena** [comment]
大佬你看下是这个吗，因为我看你的示范图片中貌似比这个多了一行。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月10日(星期五) 上午8:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DullSword/GLaDOS-CheckIn] [question/help]:项目显示成功运行，但是没有自动签到与微信推送？  (Issue #29)





 
试试重新设置下COOKIES密钥。看起来是 cookie 有非法字符，可能复制粘贴时误入了其他字符。
 
三、设置密钥

**Comment by Guichena** [comment]
> 大佬你看下是这个吗，因为我看你的示范图片中貌似比这个多了一行。
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人： ***@***.***>;发送时间： 2022年6月10日（星期五） 上午8：46 收件人： ***@***.***>;抄送： ***@***.***>;@***.****>;主题： Re： [DullSword/GLaDOS-CheckIn] [question/help]：项目显示成功运行，但是没有自动签到与微信推送？ （Issue #29） 试试重新设置下COOKIES密钥。看起来是 cookie 有非法字符，可能复制粘贴时误入了其他字符。三、设置密钥 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。您收到此消息是因为您创作了该线程。留言ID：***@**。***>

就是貌似少了前两行，-ga和-gid的这些信息我的并没有显示。
koa:sess=******; koa:sess.sig=*****; __stripe_mid=*****

**Comment by Guichena** [comment]
大佬，已经解决了，谢谢佬

**Comment by DullSword** [comment]
> 大佬你看下是这个吗，因为我看你的示范图片中貌似比这个多了一行。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年6月10日(星期五) 上午8:46 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [DullSword/GLaDOS-CheckIn] [question/help]:项目显示成功运行，但是没有自动签到与微信推送？ (Issue #29) 试试重新设置下COOKIES密钥。看起来是 cookie 有非法字符，可能复制粘贴时误入了其他字符。 三、设置密钥 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

没有内容呀😕

**Comment by Guichena** [comment]
已经好啦，谢谢佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月10日(星期五) 晚上8:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DullSword/GLaDOS-CheckIn] [question/help]:项目显示成功运行，但是没有自动签到与微信推送？  (Issue #29)





  
大佬你看下是这个吗，因为我看你的示范图片中貌似比这个多了一行。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年6月10日(星期五) 上午8:46 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [DullSword/GLaDOS-CheckIn] [question/help]:项目显示成功运行，但是没有自动签到与微信推送？ (Issue #29) 试试重新设置下COOKIES密钥。看起来是 cookie 有非法字符，可能复制粘贴时误入了其他字符。 三、设置密钥 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
没有内容呀😕

**Comment by DullSword** [comment]
> > 大佬你看下是这个吗，因为我看你的示范图片中貌似比这个多了一行。
> > [...](#)
> > ------------------ 原始邮件 ------------------ 发件人： _**@**_._**>;发送时间： 2022年6月10日（星期五） 上午8：46 收件人： _**@**_.**_>;抄送： _**@**_._**>;@**_.__**>;主题： Re： [DullSword/GLaDOS-CheckIn] [question/help]：项目显示成功运行，但是没有自动签到与微信推送？ （Issue #29） 试试重新设置下COOKIES密钥。看起来是 cookie 有非法字符，可能复制粘贴时误入了其他字符。三、设置密钥 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。您收到此消息是因为您创作了该线程。留言ID：**_@**。**_>
> 
> 就是貌似少了前两行，-ga和-gid的这些信息我的并没有显示。 koa:sess=__****; koa:sess.sig=****_; __stripe_mid=_****

签到和获取信息应该只要 koa:sess 和 koa:sess.sig 就可以。

> 大佬，已经解决了，谢谢佬

不是大佬，能用了就好。
