### ISSUE TITLE
设置定时的 cron 是什么语法规则呀

### ISSUE THREAD

**Issue by capitalwell** [DullSword/GLaDOS-CheckIn#3]
就是代码里面的
`cron: 30 1 * * *`
看博客里面表示

> # 定时运行 UTC 1点30分(北京时间 9点30分)
那么后面的星号 `* * *` 是什么意思呢

**Comment by DullSword** [comment]
[crontab的语法规则格式](https://help.aliyun.com/document_detail/64769.html)

**Comment by DullSword** [comment]
Crontab表达式：

```
┌──分钟（0 - 59）
│ ┌──小时（0 - 23）
│ │ ┌──日（1 - 31）
│ │ │ ┌─月（1 - 12）
│ │ │ │ ┌─星期（0 - 6，表示从周日到周六）
│ │ │ │ │
* * * * * 
```

>星号（*）代表任何可能的值。例如：在“小时域”里的星号等于是“每一个小时”。

可以看 [crontab的语法规则格式 - freesilo](https://freesilo.com/?p=1083) 或 [Cron - wiki](https://zh.wikipedia.org/wiki/Cron)
