### ISSUE TITLE
[Bug]: 2022-06-28

### ISSUE THREAD

**Issue by tyIceStream** [DullSword/GLaDOS-CheckIn#34]
### 分支

main

### 当前行为

2022-06-28更新导致Actions失效是由于网站开启CloudFlare导致，基于Request的爬虫策略基本都会失效。
但是我本地登陆并没有触发cloudflare，推测仅仅限制了github的节点。
目前对于该反爬机制，基于undetected-chromedriver的方案能够奏效，已实践可以签到。
(https://github.com/tyIceStream/GLaDOS_Checkin)
如果glados不关闭cloudflare，据我所知可能没有其他方案，如果有希望共同交流。
另外你的Action的log会暴露你的cookie，建议你修改一下。

### 预期行为

-

### 工作流日志

-

**Comment by yaoysyao** [comment]
1. glados如何关闭cloudflare
2. actions的log指的是什么？如何进行处理？

**Comment by AstbReal** [comment]
@tyIceStream 大佬想问一下，运行你那个代码可以使用github action实现吗？

**Comment by tyIceStream** [comment]
@AstbReal 可以的，那个是支持Github Action的，加个名为【GLADOS_COOKIE】的secret，值为网页中截取的Cookie，然后启动一下Action就可以了。我那个repo的Actions也是开着的。那个昨晚才上线，后续会在ReadMe写详细一点的启动方式的。

**Comment by AstbReal** [comment]
@tyIceStream 明白

**Comment by DullSword** [comment]
> ### 分支
> main
> 
> ### 当前行为
> 2022-06-28更新导致Actions失效是由于网站开启CloudFlare导致，基于Request的爬虫策略基本都会失效。 但是我本地登陆并没有触发cloudflare，推测仅仅限制了github的节点。 目前对于该反爬机制，基于undetected-chromedriver的方案能够奏效，已实践可以签到。 (https://github.com/tyIceStream/GLaDOS_Checkin) 如果glados不关闭cloudflare，据我所知可能没有其他方案，如果有希望共同交流。 另外你的Action的log会暴露你的cookie，建议你修改一下。
> 
> ### 预期行为
> 
> ### 工作流日志

看起来确实和 CloudFlare 有关，返回的是 CloudFlare的 DDos 保护页面。有可能是限制了 github，同时测试时发现使用 postman 模拟发送请求也会出现该情况，而本地则可以成功请求。搜了一圈，感觉没有什么简单完美的方案。

我以为其他人是点不进我项目的 "Actions"，结果居然可以😲。

**Comment by AngryBigCat** [comment]
换成其他的代码托管平台 然后用持续集成写jenkins 也能解决

**Comment by TRHX** [comment]
CloudFlare 五秒盾可以通过 JS 逆向绕过
