### ISSUE TITLE
[Bug]:  cookie过期

### ISSUE THREAD

**Issue by byeice** [DullSword/GLaDOS-CheckIn#35]
### 分支

main

### 当前行为

昨天开始提醒  cookie过期，更新cookie 仍然提示cookie过期，无法签到

### 预期行为

无法签到

### 工作流日志

无

**Comment by 3qp** [comment]
我这也签到不了了。

**Comment by yaoysyao** [comment]
现有的方法好像不行了，可以试试我的的那个，在github其他大佬的基础上新增了签到信息推送到pushplus平台，如果需要server酱的话，后续也可以增加，目前我的仓库那个项目还是可以签到的

**Comment by DullSword** [comment]
#34
