### ISSUE TITLE
[question/help]: 签到时提示错误 AxiosError: Request failed with status code 503

### ISSUE THREAD

**Issue by dlagez** [DullSword/GLaDOS-CheckIn#36]
### 问题

遇到错误：AxiosError: Request failed with status code 503
<img width="447" alt="image" src="https://user-images.githubusercontent.com/62829603/177005034-89379499-4404-49a5-a404-2bb5d136ae27.png">

**Comment by yaoysyao** [comment]
现在这种方法已经失效了，没办法签到了，可以试试我的仓库里面的代码：https://github.com/yaoysyao/GLaDOS_Auto_Checkin.git
在其他大佬的基础上增加了推送消息到pushplus,目前还是可以签到的

**Comment by DullSword** [comment]
- #34
