### ISSUE TITLE
[Bug]: GLADOS要求付费升级，不能再通过签到免费使用

### ISSUE THREAD

**Issue by Thund1R** [DullSword/GLaDOS-CheckIn#38]
### 分支

main

### 当前行为

![image](https://user-images.githubusercontent.com/31063519/177825649-43bef515-ee0c-4bec-8687-aec1d724d3a5.png)
没有有效的会员资格无法签到，请升级到基本/专业计划

### 预期行为

正常签到并延长到期时间

### 工作流日志

无

**Comment by PamlJam** [comment]
same

**Comment by RouJiANG-14** [comment]
遇到的同样的问题，看来是更改政策了？？？

**Comment by DullSword** [comment]
如果是学生，可以申请[教育计划](https://glados.rocks/console/education)。
