### ISSUE TITLE
[question/help]: 如果不差钱的话，冲个会员吧。这个vpn挺良心的，至少比爱奇艺、腾讯视频的年会会员划得来吧

### ISSUE THREAD

**Issue by Louis14lan** [DullSword/GLaDOS-CheckIn#39]
### 问题

如果不差钱的话，还是冲个会员吧。我用过很多梯子，这个梯算是最良心的，性价比最高的，网络最稳定的，也是用的最久的梯子，希望别被大家给薅没了。至少比冲爱奇艺、腾讯视频的年会会员划得来吧，学生党若没钱可申请教育版

**Comment by Louis14lan** [comment]
我之前也产生过写脚本的念想，后来感觉它挺良心的，就没忍薅它

**Comment by DullSword** [comment]
理解，GLaDOS 用来冲浪是挺不错的，而且有教育计划，在README里就有提及。

当时写这个项目出于三个目的：

- 练手
- 老是忘记签到&懒
- 帮助偶尔需要冲浪的人

一个月后发现签到只有33%概率送一天，而用了一个月感觉挺好的，所以当时就开了套餐。

最后提一下，GLaDOS 加了防护，目前该项目已经无法正常签到，而且 GLaDOS 已经改变了签到策略，免费套餐无法签到。
