### ISSUE TITLE
教育用户不能签到了

### ISSUE THREAD

**Issue by cxh2959540834** [DullSword/GLaDOS-CheckIn#48]
### 问题

教育用户不能签到了

**Comment by DullSword** [comment]
官网上可以签到吗？返回的提示是什么呢？

没有教育账户，没办法自己测试😢

**Comment by gmfhaha** [comment]
> ### 问题
> 教育用户不能签到了

我的教育用户也不能签到了。在弄了自动签到后就不行了，没有享受过一次的自动签到，现在教育用户也不能签到了，让我花钱升级才能签到

**Comment by hankangwen** [comment]
返回是
Free users can not checkin anymore, please upgrade to Basic/Pro plan

**Comment by gmfhaha** [comment]
> 返回是 Free users can not checkin anymore, please upgrade to Basic/Pro plan

请问是该系统不让教育用户签到了吗？

**Comment by huangtianxing** [comment]
我的也是，应该是不能薅羊毛了

**Comment by gmfhaha** [comment]
> 

可是为什么是在我弄完自动签到后，才不能签到？这么巧的嘛？伤心，早知就不弄什么自动签到了。

**Comment by DullSword** [comment]
> 返回是 Free users can not checkin anymore, please upgrade to Basic/Pro plan

官网上签到是这样，那就没办法了，可能是规则改了。
