### ISSUE TITLE
github封了几个号了[question/help]: 

### ISSUE THREAD

**Issue by 546220777** [DullSword/GLaDOS-CheckIn#49]
### 问题

跑这玩意儿  2天封一个号！！！！！

**Comment by DullSword** [comment]
呃，没碰过到这种情况，也没其他人反馈，真要封也应该是GLaDOS封号吧，github封号我想不出什么理由呀，比起其他一些项目，这通常只用了1分钟，发了几个请求就退出了，没占用特别多资源。要不您再看看，会不会是其他原因导致的？

**Comment by ZiuChen** [comment]
主要原因大概是小号滥用Github Action吧
