### ISSUE TITLE
[question/help]: 偶尔每天可以签到两次

### ISSUE THREAD

**Issue by SainoNamkho** [DullSword/GLaDOS-CheckIn#53]
### 问题

请问服务器刷新的时间是否有规律？我发现偶尔能一天能获得两次使用时长

**Comment by DullSword** [comment]
- #12 

之前尝试过研究，未果。我发现扣除天数和重置签到似乎不是同一时间进行。

**Comment by SainoNamkho** [comment]
> * [签到无法获得天数的问题 #12](https://github.com/DullSword/GLaDOS-CheckIn/issues/12)
> 
> 之前尝试过研究，未果。我发现扣除天数和重置签到似乎不是同一时间进行。

谢谢
