### ISSUE TITLE
[question/help]: 正常签到1个月之后无法签到

### ISSUE THREAD

**Issue by llstela** [DullSword/GLaDOS-CheckIn#60]
### 问题

我是22年9月14号开始使用这个项目进行自动签到的。之前一直都能自动签到。但是从22年10月21日左右开始，pushplus停止向我推送签到成功的信息，GLaDOS的官方签到页面也处于未签到状态；但是点开github的action，可以发现[GLaDOS-CheckIn](https://github.com/llstela/GLaDOS-CheckIn/actions/runs/3305571844)依然每天正常运行。

但是不知道为什么签到是失败的，我昨天在配置文件中还重新填写了签到的Cookie和pushplus的token，但是今天依然没有自动签到。

**Comment by DullSword** [comment]
更新代码试试。

![fetch_upstream](https://user-images.githubusercontent.com/40877476/197384192-e0fd224c-db06-4da2-8abf-b64632b42043.png)

- #57 
- #56

**Comment by tianwuziyan** [comment]
我也是同样的问题，无法签到

**Comment by llstela** [comment]
> 更新代码试试。
> 
> ![fetch_upstream](https://user-images.githubusercontent.com/40877476/197384192-e0fd224c-db06-4da2-8abf-b64632b42043.png)
> 
> * [fiX：锁定及提升版本 #57](https://github.com/DullSword/GLaDOS-CheckIn/pull/57)
> * [[question/help]: 运行checkin脚本报错 An `executablePath` or `channel` must be specified for `puppeteer-core` #56](https://github.com/DullSword/GLaDOS-CheckIn/issues/56)

OK，update之后可以了。
