### ISSUE TITLE
多个账户签到后可以同时给两个账号推送pushplus消息吗[question/help]: 

### ISSUE THREAD

**Issue by PavoneB** [DullSword/GLaDOS-CheckIn#61]
### 问题

cookie那里添加多个账户签到后，可以同时给两个账号都推送pushplus消息吗

**Comment by Zeal599** [comment]
你今天还能用吗？

**Comment by yulelong** [comment]
> 

微信通知里面会合并显示两个帐号的签到情况啊

**Comment by DullSword** [comment]
[README](https://github.com/DullSword/GLaDOS-CheckIn#readme) 里开头有效果图，图上就是两个账号的签到情况。

**Comment by DullSword** [comment]
> 你今天还能用吗？

需要更新代码
