### ISSUE TITLE
如何设置多用户的cookie

### ISSUE THREAD

**Issue by mikemhm** [DullSword/GLaDOS-CheckIn#7]

**Comment by DullSword** [comment]
最新版本已支持多账号。如果有用到推送的话，需要考虑是否使用新版本，因为推送平台由 [Server酱](https://sc.ftqq.com/) 更换为了 [pushplus(推送加)](https://www.pushplus.plus/)，原因可以查看文档中的 [更新日志](https://github.com/DullSword/GLaDOS-CheckIn#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97) 部分。

使用最新版本：
- 想用到推送则需要 pushplus的 token，详情见 [一、准备工作](https://github.com/DullSword/GLaDOS-CheckIn#%E4%B8%80%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C)
- 重新设置密钥，详情见 [三、设置密钥](https://github.com/DullSword/GLaDOS-CheckIn#%E4%B8%89%E8%AE%BE%E7%BD%AE%E5%AF%86%E9%92%A5)
- 同步版本，详情见 [更新日志](https://github.com/DullSword/GLaDOS-CheckIn#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)
