### ISSUE TITLE
Cookie多久过期？需不要定期更新Cookie?

### ISSUE THREAD

**Issue by Arisono** [DullSword/GLaDOS-CheckIn#9]

**Comment by DullSword** [comment]
![cookie](https://user-images.githubusercontent.com/40877476/160632656-d9ede798-fa87-4ad4-a587-4c5ce6d337d9.png)
可以自行查看。

常规来说，服务端会在用户登陆后选择性地更新cookie的maxage。我看了下GLaDOS不是每次登陆都会更新，可能是maxage剩余一个月或一周之类的时候才会更新，具体是什么规则，这得看它那边的实现了。目前的情况是，项目从始至终一年多的时间内，我是没有因为过期的原因更新过cookie，也没有出现这类issue，预测不用担心。

**Comment by Arisono** [comment]
我用老版本的时候，出现过一个月之后，GlaDOS就不让签到的现象。这次我继续观察，看下会不会出现。

**Comment by DullSword** [comment]
> 我用老版本的时候，出现过一个月之后，GlaDOS就不让签到的现象。这次我继续观察，看下会不会出现。

好的，出现时可以查看下log，可能就能发现问题了，或者将个人信息隐藏后发issue。

![log](https://user-images.githubusercontent.com/40877476/160772996-0bec354b-3899-45c9-89e7-fcecdcd2e786.jpg)

也可能是 Github Actions 出现故障 #5 。
